### ISSUE TITLE
UTF8 Converter

### ISSUE THREAD

**Issue by nhlpl** [akhoury/nodebb-plugin-import#108]
UTF8 Database Converter have to be used before using NodeBB Import Tool.

At this moment nodebb-plugin-import breaks non-latin charakcters.
ą > ±
ć > æ
ę > ê
ł > ³
ń > ñ
ś > ¶
ż > ¿

SQL System Variables for IP.Board 2.3.x

collation_connection: latin1_swedish_ci
collation_database: latin1_swedish_ci
collation_server: latin1_swedish_ci

character_set_client: latin1
character_set_connection: latin1
character_set_database: latin1

character_set_results: latin1
character_set_server: latin1
character_set_system: utf8

**Comment by akhoury** [comment]
can you suggest a module that does that? I'll gladly add it.

**Comment by nhlpl** [comment]
Do you think about npm modules like this one?
https://www.npmjs.com/package/gulp-convert-encoding

**Comment by akhoury** [comment]
more like https://github.com/ashtuchkin/iconv-lite which is used by gulp-convert-encoding, thanks for the lead

**Comment by nhlpl** [comment]
Do you need any additional support to make it work? I'll be happy to test it out when it gets ready.

**Comment by akhoury** [comment]
I would love to have to a sample DB dump to test with my self.

**Comment by sohrabafard** [comment]
Hello,
about "vbulletin" to "nodebb" migration using nodebb import plugin, the contents were transferred as follows:

Ù„Ø·ÙØ§ ÙÙ‚Ø· Ú©ØªØ¨ Ùˆ Ø¬Ø²ÙˆØ§ØªÛŒ Ø±Ø§ Ù‚Ø±Ø§Ø± Ø¯Ù‡ÛŒØ¯ Ú©Ù‡ Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡ ÛŒ Ø¢Ù† Ù‡Ø³ØªÛŒØ¯ Ùˆ ÛŒØ§ Ø§Ø² Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡ ÛŒ Ø¢Ù† Ø§Ø¬Ø§Ø²Ù‡ Ø¯Ø§Ø±ÛŒØ¯.

correct form is :

لطفا فقط کتب و جزواتی را قرار دهید که نویسنده ی آن هستید و یا از نویسنده ی آن اجازه دارید.

Who can help me?

**Comment by akhoury** [comment]
let me see what I can do. Im gonna close this one here https://github.com/akhoury/nodebb-plugin-import-vbulletin/issues/4, as they are duplicates

**Comment by sohrabafard** [comment]
thanks,
When I copy any corrupted text in notepad++ and then convert it from ansi to utf8 ,
text will be ok...

**Comment by akhoury** [comment]
@sohrabafard can you provide me a with database dump to test with? feel free to send it privately to email bentael@gmail.com, and to obfuscate emails, password and other data unless you want to trust me with it :)

**Comment by sohrabafard** [comment]
I will send two tables vb_thread and vb_post that have bunch of utf8 data ( about 1.5K records )
with foratmail@gmail.com.
.
each Table:
Type:	InnoDB
Collation:	utf8_general_ci

Thanks a lot!

**Comment by sohrabafard** [comment]
an idea : 
make a plugin that iterate on nodebb Posts, Category, ... and change encoding of text from ANSI to "UTF-8" :

https://community.nodebb.org/topic/7213/iterate-on-nodebb-posts

**Comment by sohrabafard** [comment]
let me know, if you get my mail!

**Comment by sohrabafard** [comment]
13/12 03:26 [8180] - error: ReferenceError: encoding is not defined
			at eval (eval at <anonymous> (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:339:18), <anonymous>:3:11)
			at Object.Controller.convert (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:368:34)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1266:87
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:567:21
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:246:17
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:122:13
			at _each (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:46:13)
			at async.each (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:121:9)
			at _asyncMap (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:245:13)
			at Object.map (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:216:23)
		ReferenceError: encoding is not defined
			at eval (eval at <anonymous> (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:339:18), <anonymous>:3:11)
			at Object.Controller.convert (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:368:34)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1266:87
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:567:21
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:246:17
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:122:13
			at _each (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:46:13)
			at async.each (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:121:9)
			at _asyncMap (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:245:13)
			at Object.map (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:216:23)

**Comment by akhoury** [comment]
i know why, hang on will fix it in an hour.

**Comment by akhoury** [comment]
actually just be fixed now

**Comment by sohrabafard** [comment]
in Topic Title:

		13/12 05:00 [9592] - error: TypeError: undefined is not a function
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/bbcode-to-markdown.js:24:31
			at Object.Controller.convert (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:368:24)
			at Data.eachGroup.async (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1225:25)
			at replenish (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:191:21)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:203:33
			at nxt (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1220:12)
			at Data.eachGroup.async (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1229:12)
			at replenish (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:191:21)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:203:33
			at nxt (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1220:12)
		TypeError: undefined is not a function
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/bbcode-to-markdown.js:24:31
			at Object.Controller.convert (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:368:24)
			at Data.eachGroup.async (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1225:25)
			at replenish (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:191:21)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:203:33
			at nxt (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1220:12)
			at Data.eachGroup.async (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1229:12)
			at replenish (/home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:191:21)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:203:33
			at nxt (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1220:12)

**Comment by sohrabafard** [comment]
and this error:

		13/12 05:03 [9720] - error: TypeError: undefined is not a function
			at Object.module.exports.utils.slugify (/home/nodeBB/forum/public/src/utils.js:81:14)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1310:88
			at /home/nodeBB/forum/src/database/mongo/hash.js:15:4
			at handleCallback (/home/nodeBB/forum/node_modules/mongodb/lib/utils.js:96:12)
			at /home/nodeBB/forum/node_modules/mongodb/lib/collection.js:974:5
			at /home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:778:13
			at Callbacks.emit (/home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
			at null.messageHandler (/home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
			at Socket.<anonymous> (/home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:297:20)
			at Socket.emit (events.js:107:17)
		TypeError: undefined is not a function
			at Object.module.exports.utils.slugify (/home/nodeBB/forum/public/src/utils.js:81:14)
			at /home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1310:88
			at /home/nodeBB/forum/src/database/mongo/hash.js:15:4
			at handleCallback (/home/nodeBB/forum/node_modules/mongodb/lib/utils.js:96:12)
			at /home/nodeBB/forum/node_modules/mongodb/lib/collection.js:974:5
			at /home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:778:13
			at Callbacks.emit (/home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
			at null.messageHandler (/home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
			at Socket.<anonymous> (/home/nodeBB/forum/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:297:20)
			at Socket.emit (events.js:107:17)

**Comment by sohrabafard** [comment]
so we have just **two error**:

first on:

     Topics titles and content

that is: 

    13/12 05:03 [9720] - error: TypeError: undefined is not a function
        at Object.module.exports.utils.slugify (/home/nodeBB/forum/public/src/utils.js:81:14)
        at /home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:1310:88
    ...

second on:

    BB-Code to MarkDown

that is:

        13/12 05:00 [9592] - error: TypeError: undefined is not a function
        at /home/nodeBB/forum/node_modules/nodebb-plugin-import/node_modules/bbcode-to-markdown/bbcode-to-markdown.js:24:31
        at Object.Controller.convert (/home/nodeBB/forum/node_modules/nodebb-plugin-import/server/controller.js:368:24)
    ...

**and user,Category name and description,Private Message, user signature have no problem.**

**Comment by sohrabafard** [comment]
secound problem solved buy running this command:

    npm install bbcode-to-markdown

**So I recommend you to add bbcode-to-markdown to dependecy.**

**Comment by akhoury** [comment]
it is added as dependency. https://github.com/akhoury/nodebb-plugin-import/blob/master/package.json#L44 

something is wrong with your installation.

**Comment by sohrabafard** [comment]
i install plugin using npm,
what about first error?

**Comment by akhoury** [comment]
can you show me your parseBefore function syntax ? you're not passing a string through.

**Comment by sohrabafard** [comment]
content = encoding.convert(content,"windows-1252","utf8");

**Comment by akhoury** [comment]
```
console.log(typeof encoding.convert("test","windows-1252","utf8")); // prints object

```

use this instead, basically just add `toString()` to it.
```
 content = encoding.convert(content,"windows-1252","utf8").toString();
```

**Comment by sohrabafard** [comment]
Yes, the problem was solved!

please close issue!

Thanks a lotو
