### ISSUE TITLE
Error when set a large pre-parse script

### ISSUE THREAD

**Issue by freeznet** [akhoury/nodebb-plugin-import#133]
I have got this error when I set a 500+ lines pre-parse script.

```
28/10 11:15 [27364] - error: /api/admin/plugins/import/config
 Error: request entity too large
    at readStream (/var/nodebb/node_modules/body-parser/node_modules/raw-body/index.js:185:17)
    at getRawBody (/var/nodebb/node_modules/body-parser/node_modules/raw-body/index.js:95:12)
    at read (/var/nodebb/node_modules/body-parser/lib/read.js:68:3)
    at urlencodedParser (/var/nodebb/node_modules/body-parser/lib/types/urlencoded.js:109:5)
    at Layer.handle [as handle_request] (/var/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/nodebb/node_modules/express/lib/router/index.js:271:10)
    at favicon (/var/nodebb/node_modules/serve-favicon/index.js:72:7)
Error: misconfigured csrf
    at getsecret (/var/nodebb/node_modules/csurf/index.js:195:11)
    at Object.csrf [as applyCSRF] (/var/nodebb/node_modules/csurf/index.js:60:18)
    at Object.middleware.buildHeader (/var/nodebb/src/middleware/middleware.js:175:13)
    at /var/nodebb/src/routes/index.js:220:15
    at Layer.handle_error (/var/nodebb/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/nodebb/node_modules/express/lib/router/index.js:310:13)
    at /var/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/var/nodebb/node_modules/express/lib/router/layer.js:67:12)
```

**Comment by akhoury** [comment]
Hmm looks like a body-parser error, let me see if I can increase the limit
or workaround it.

How big is your script though? Can you share it? Does it make sense to
write a quick script and run it as a standalone?

**Comment by akhoury** [comment]
can you try this:

Find NodeBB/src/middleware/index, lines 48, 49 and increase the limit on the body parser. Set it appropriately, not sure how big of body you're sending but that's gotta be bigger than the default 100kb.

So change.

From:
```javascript
48:	app.use(bodyParser.urlencoded({extended: true}));
49:	app.use(bodyParser.json());
```

To, 
```javascript
48:	app.use(bodyParser.urlencoded({extended: true, limit: '100mb'}));
49:	app.use(bodyParser.json({limit: '100mb'}));
```

then restart NodeBB and try again. that worked for me.

**Comment by akhoury** [comment]
closing as this is not a plugin issue.
