### ISSUE TITLE
"ERR value is not a valid float" at votes import

### ISSUE THREAD

**Issue by bdharrington7** [akhoury/nodebb-plugin-import#145]
Have you come across this error before? I did `git co v0.9.x` (before I read that the importer wasn't compatible with 0.9.3+ yet), and got this error, so then I downgraded nodebb to the `v0.9.2` tag and did `npm rebuild`

```
[nodebb-plugin-import] importer.success [2015-12-26T16:27:24.214Z] Importing 6079 votes.
26/12 08:27 [54292] - error: Error: ERR value is not a valid float
    at JavascriptReplyParser._parseResult (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:114:21)
    at JavascriptReplyParser.run (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:126:22)
    at JavascriptReplyParser.execute (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/Users/brian/github/NodeBB/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
Error: ERR value is not a valid float
    at JavascriptReplyParser._parseResult (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:114:21)
    at JavascriptReplyParser.run (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:126:22)
    at JavascriptReplyParser.execute (/Users/brian/github/NodeBB/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/Users/brian/github/NodeBB/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

I noticed that there is one vote record that gets imported at the key `_imported_vote`, but there are no keys at `_imported:_votes`

**Comment by akhoury** [comment]
hmm ive seen this before with redis only, seems like redis is not forgiving some type.
ill check that out.

**Comment by bdharrington7** [comment]
It only happens on votes and bookmarks.

-Brian

**Comment by akhoury** [comment]
which version of the import-plugin are u using?

trying to find out if these 2 lines are the issue

### votes
https://github.com/akhoury/nodebb-plugin-import/blob/master/server/importer.js#L1878
```javascript
// now
Data.setVoteImported(_vid, _vid /* there's no vote.vid */, vote, done);

// try to change it to this, basically replace the 2nd argument by 0, since we dont care about ordering
Data.setVoteImported(_vid, 0 /* there's no vote.vid */, vote, done);
```

### bookmarks
https://github.com/akhoury/nodebb-plugin-import/blob/master/server/importer.js#L1990

```javascript
// now
Data.setBookmarkImported(_bid, _bid /* there's no bookmark.bid */, bookmark, done);

// try to change it to this, basically replace the 2nd argument by 0, since we dont care about ordering
Data.setBookmarkImported(_bid, 0 /* there's no bookmark.bid */, bookmark, done);
```

related commit: 
https://github.com/akhoury/nodebb-plugin-import/commit/63cb569926002e113290b975c5f26c83a1c34e15

So, if the 2nd argument, (when i am also using `_bid` or `_vid`) is not a numbers, shit may occur [here](https://github.com/NodeBB/NodeBB/blob/a054353b6c9896693bfb9c64e7e389380bff1ea1/src/database/redis/sorted.js#L12-L14) where calling `redis.zadd` on a non number.

I bet that doesn't happen in Mongo though

**Comment by akhoury** [comment]
http://redis.io/commands/ZADD
> The score values should be the string representation of a double precision floating point number. +inf and -inf values are valid values as well.

or you can catch the error early, log out the error and the _bid as well, this way we can tell what it is.

```javascript
Data.setBookmarkImported(_bid, _bid /* there's no bookmark.bid */, bookmark, function(err) {
    if (err) {
         console.error("setBookmarkImported:errored", _bid, typeof _bid, err);
         return done(err);
    }
});
```

**Comment by bdharrington7** [comment]
Yeah that's probably the change that broke it for redis, I'm using the latest importer on master

-Brian

**Comment by bdharrington7** [comment]
I'm sure that's what it is because for bookmarks and votes, there's no "ID" in the sense of a numerical value that's unique to that record, so I had to create one that was unique by concatenating information that makes it unique, like 'pid_uid'

**Comment by akhoury** [comment]
Ahh, that makes sense, I should stop using the ids as score then, we don't really need them

**Comment by akhoury** [comment]
thanks @bdharrington7 for https://github.com/akhoury/nodebb-plugin-import/pull/146

**Comment by bdharrington7** [comment]
:+1:
