### ISSUE TITLE
Crash loading topic after fresh import

### ISSUE THREAD

**Issue by CarlosRodriguez1982** [akhoury/nodebb-plugin-import#147]
Hello.

After importing crashes loading any imported topic, the other topics can be loaded.

Tested with fresh SMF and MyBB installations, with the last version that was compatible with NodeBB 0.9.1 and the current version 0.3.24 compatible with 0.9.2 following the instructions in readme with their respective NodeBB versions.

Just after loading a topic:

3/1 18:18 [8088] - info: NodeBB is now listening on: 0.0.0.0:4567
3/1 18:18 [8088] - error: RangeError: Invalid time value
    at Date.toISOString (native)
    at Object.module.exports.utils.toISOString (/home/desktop/NodeBB/public/src/utils.js:211:74)
    at /home/desktop/NodeBB/src/posts.js:60:70
    at /home/desktop/NodeBB/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/home/desktop/NodeBB/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/home/desktop/NodeBB/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/desktop/NodeBB/node_modules/async/lib/async.js:337:20)
    at async.waterfall.plugins.fireHook.posts (/home/desktop/NodeBB/src/posts.js:54:11)
    at fn (/home/desktop/NodeBB/node_modules/async/lib/async.js:741:34)
    at /home/desktop/NodeBB/node_modules/async/lib/async.js:1208:16
RangeError: Invalid time value
    at Date.toISOString (native)
    at Object.module.exports.utils.toISOString (/home/desktop/NodeBB/public/src/utils.js:211:74)
    at /home/desktop/NodeBB/src/posts.js:60:70
    at /home/desktop/NodeBB/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/home/desktop/NodeBB/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/home/desktop/NodeBB/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/desktop/NodeBB/node_modules/async/lib/async.js:337:20)
    at async.waterfall.plugins.fireHook.posts (/home/desktop/NodeBB/src/posts.js:54:11)
    at fn (/home/desktop/NodeBB/node_modules/async/lib/async.js:741:34)
    at /home/desktop/NodeBB/node_modules/async/lib/async.js:1208:16
3/1 18:18 [8088] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
3/1 18:18 [8088] - info: [app] Database connection closed.
3/1 18:18 [8088] - info: [app] Web server closed to connections.
3/1 18:18 [8088] - info: [app] Shutdown complete.
desktop@ns3001735:~/NodeBB$ 

In the case they are outdated, is there an exporter that is known to work with the current version so I can import my forum?

Thanks.
Carlos

**Comment by bdharrington7** [comment]
This should be fixed in the latest (0.3.25)

-Brian

**Comment by akhoury** [comment]
ah, the `edited="undefined"` thing? am i right @bdharrington7 ? is so, then the latest release should have fixed that.

**Comment by bdharrington7** [comment]
IIRC that's the error that happens when edited = undefined, yes

-Brian

**Comment by CarlosRodriguez1982** [comment]
Is there a way to get the latest dev version with that fix before 0.3.25 gets released?

Cogratulations for all NodeBB contributors for your great work.

**Comment by bdharrington7** [comment]
Yeah, just clone the repo into your node_modules folder

**Comment by akhoury** [comment]
@CarlosRodriguez1982 I just published [nodebb-plugin-import@0.3.25](https://www.npmjs.com/package/nodebb-plugin-import)
