### ISSUE TITLE
TypeError: Cannot set property 'filepath' of null

### ISSUE THREAD

**Issue by cp-nilly** [akhoury/nodebb-plugin-import#149]
Stack trace:
```
[nodebb-plugin-import] importer.success [2016-01-08T14:49:38.550Z] Imported 9069/9344 messages
[nodebb-plugin-import] importer.success [2016-01-08T14:49:41.001Z] Importing 2613 topics.
8/1 09:49 [5912] - error: TypeError: Cannot set property 'filepath' of null
    at writeBlob (/home/***/NodeBB/node_modules/nodebb-plugin-import/server/importer.js:692:18)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/server/importer.js:1445:13
    at replenish (/home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:191:21)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:208:15
    at Object.async.eachLimit (/home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:168:12)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/server/importer.js:1441:18
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:251:17
    at done (/home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:132:19)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:32:16
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:248:21
TypeError: Cannot set property 'filepath' of null
    at writeBlob (/home/***/NodeBB/node_modules/nodebb-plugin-import/server/importer.js:692:18)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/server/importer.js:1445:13
    at replenish (/home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:191:21)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:208:15
    at Object.async.eachLimit (/home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:168:12)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/server/importer.js:1441:18
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:251:17
    at done (/home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:132:19)
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:32:16
    at /home/***/NodeBB/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:248:21
```

I'm pretty sure it is a problem with _attachmentsBlobs. Worked fine under v0.3.25. Problem cropped up when I updated to v0.3.29.

**Comment by akhoury** [comment]
hmm - it seems like `fileType(buffer)` is returning `null` for a some type of buffer.

**Comment by akhoury** [comment]
i'd be interested to know which blob did that.

**Comment by akhoury** [comment]
try 0.3.30

**Comment by akhoury** [comment]
I started using this module, [file-type](https://www.npmjs.com/package/file-type) to detect the mime type of each attachment, so if it's an image, I'd add it as an `<img>` tag instead of just an `<a>`

**Comment by cp-nilly** [comment]
Yea, that fixed it. Thanks. :)
