### ISSUE TITLE
Error: WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by cp-nilly** [akhoury/nodebb-plugin-import#154]
Stack trace:
```
10/1 06:44 [15406] - error: /api/category/4/discussion
 Error: WRONGTYPE Operation against a key holding the wrong kind of value
    at JavascriptReplyParser._parseResult (/home/***/NodeBB/node_modules/redis/lib/parsers/javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (/home/***/NodeBB/node_modules/redis/lib/parsers/javascript.js:114:21)
    at JavascriptReplyParser.run (/home/***/NodeBB/node_modules/redis/lib/parsers/javascript.js:135:22)
    at JavascriptReplyParser.execute (/home/***/NodeBB/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/home/***/NodeBB/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
```

Seems to happen when one makes use of _level = "moderator" for user imports. This error happens whenever I try to visit any category after importing users that have _level set to "moderator".

**Comment by cp-nilly** [comment]
Might also happen with "administrator" set. I'm using a dump that only has 1 administrator. The nodebb admin takes over the administrator of the dump.

**Comment by akhoury** [comment]
this one is a little weird. I'll take a look.
By the way, any reason you're using redis and not mongo?

**Comment by akhoury** [comment]
I think i know why.

**Comment by akhoury** [comment]
i think i fixed it.

**Comment by cp-nilly** [comment]
Thanks. It's fixed now. :)

I use redis in other projects. I want to do some integration with those projects and the forum and figured it would easier if both shared the same db. Perhaps I'm wrong with this assumption. Other than that, redis is familiar while mongo is something I've never used before.

**Comment by akhoury** [comment]
no worries - my only problem with redis is that you need to keep adding RAM as your DB increases (and you could potentially loose data on crashes) other than that, its fast
