### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by xidui** [akhoury/nodebb-plugin-import#192]
```
[nodebb-plugin-import] importer.success [2016-06-08T08:45:12.589Z] Phase ::: rebanAndMarkReadForUsersStart

rebanAndMarkReadForUsersStart ::: 376499/404828, 93.0022132856423%8/6 16:46 [91020] - error: RangeError: Maximum call stack size exceeded
    at Socket.flush (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/socket.js:413:32)
    at emitNone (events.js:85:20)
    at WebSocket.emit (events.js:179:7)
    at Array.<anonymous> (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/transports/websocket.js:109:14)
    at _stream_writable.js:383:15
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)
RangeError: Maximum call stack size exceeded
    at Socket.flush (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/socket.js:413:32)
    at emitNone (events.js:85:20)
    at WebSocket.emit (events.js:179:7)
    at Array.<anonymous> (/Users/xidui/Documents/xidui/github/NodeBB/node_modules/engine.io/lib/transports/websocket.js:109:14)
    at _stream_writable.js:383:15
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:775:12)

```

**Comment by akhoury** [comment]
hmm.. can you provide the following:

* OS you're using
* NodeBB version
* database type
* which exporter

**Comment by xidui** [comment]
1. Mac OSX 10.10.5 
2. The latest commit is 01aeb45
3. mongodb
4. https://github.com/xidui/nodebb-plugin-import-q2a

**Comment by akhoury** [comment]
does it do the same with NodeBB v1.0.0

see https://github.com/akhoury/nodebb-plugin-import#latest-version-only-supports

**Comment by timkock** [comment]
@xidui I have had this in a different area, it might help to increase the call stack for these kind of actions. In my case I had it when running `./nodebb upgrade` because of a massive database and the way NodeBB is built.

This did it for me in my case
`/bin/bash -c "ulimit -s 65500; exec /usr/local/bin/node --stack-size=65500 ./nodebb upgrade"`
