### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by jffz** [akhoury/nodebb-plugin-import#199]
Got an error after enabling imoprt plugin (desactivated all others plugins) and nodebb doesn't load

````
- error: Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/opt/nodebb/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/nodebb/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/nodebb/node_modules/jsdom/lib/jsdom/browser/index.js:5:21)
    at Module._compile (module.js:409:26)
Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/opt/nodebb/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/nodebb/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/nodebb/node_modules/jsdom/lib/jsdom/browser/index.js:5:21)
    at Module._compile (module.js:409:26)
````

**Comment by jffz** [comment]
fixed it :x

**Comment by akhoury** [comment]
what was it?

**Comment by jffz** [comment]
I dont really know, rebuilding node_modules filer fixed it
