### ISSUE TITLE
idle by event

### ISSUE THREAD

**Issue by jffz** [akhoury/nodebb-plugin-import#200]
Just triied to migrate my discourse install to nodebb, when i launch the postgres import, the import moudle show me : connected to databse for 1 second then goes to : State: idle, by event: | Phase: Progress: 0% and is sutck here, any idea ? :/

**Comment by jffz** [comment]
I've managed to fix firsts steps to make the plugin running. The import starts but blocks on bookmarksImportStart

````
State: idle, by event: | Phase: bookmarksImportStart Progress: 0/1, 0.0000000%
````

Logs from nodebb itself
````
[nodebb-plugin-import] importer.success [2016-06-28T20:25:01.512Z] Phase ::: bookmarksImportStart

importer.phase { phase: 'bookmarksImportStart',
  data: undefined,
  timestamp: 1467145501512 }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.success [2016-06-28T20:25:01.518Z] Importing 0 bookmarks.

[nodebb-plugin-import] importer.success [2016-06-28T20:25:01.518Z] Importing 0 bookmarks.
28/6 22:25 [32722] - [31merror[39m: error: could not determine data type of parameter $4
    at Connection.parseE (/opt/nodebb/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/opt/nodebb/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/opt/nodebb/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
error: could not determine data type of parameter $4
    at Connection.parseE (/opt/nodebb/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/opt/nodebb/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/opt/nodebb/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
````

I've looked at this issue #165 and tried the different solutions (removing dirty files) but none works, still stuck after posts importation, i can see posts and categories in my forum.

**Comment by akhoury** [comment]
this error is throw by the postgres db client, `pg`, I have no way of reproducing that without a data dump and the exact version of postgres that you are using.

**Comment by jffz** [comment]
was using pgsql9.3 (docker) and my postgres db was really light (forum aged less tahn one month).

But anyway, i stopped the import here and finalized manualy, works well =)
