### ISSUE TITLE
Nodebb v1.0.0 won't start after activating, attempts to restart 3 times.  

### ISSUE THREAD

**Issue by Holyphoenix** [akhoury/nodebb-plugin-import#202]
The text when running ./nodebb log (or rather node nodebb log in my case)
at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
20/7 21:43 [10560] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
20/7 21:43 [10560] - info: [app] Database connection closed.
20/7 21:43 [10560] - info: [app] Web server closed to connections.
20/7 21:43 [10560] - info: [app] Shutdown complete.

I should mention I am testing this on my local Windows machine.  I'm trying to test converting a mybb forum before actually doing it on the live server.  I may even just do a local migrate and then push it to my server once it looks good.  

Issue seems to be nodebb-plugin-import as I haven't activated nodebb-plugin-import-mybb yet.  Disabling the plugin allows nodebb to run just fine.  Double checked I was on version 1.0.0 in the dashboard.

**Comment by akhoury** [comment]
can you paste the whole log file in here, what you pasted is just a tail of the log file, it should be in
`/your/path/to/nodebb/logs/output.log`

so if you are on window

```bash
type logs/output.log
```
or open it in an editor 

By the way, you dont need to activate the `nodebb-plugin-import-mybb` plugin - it gets picked up by its own by the core importer plugin, `nodebb-plugin-import`

**Comment by Holyphoenix** [comment]
This is what I see:
Error: Could not locate the bindings file. Tried:
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\build\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\build\Debug\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\build\Release\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\out\Debug\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\Debug\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\out\Release\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\Release\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\build\default\contextify.node
 → C:\Users\Jimmydev\NodeBB\node_modules\contextify\compiled\6.3.0\win32\x64\contextify.node
    at bindings (C:\Users\Jimmydev\NodeBB\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\Users\Jimmydev\NodeBB\node_modules\contextify\lib\contextify.js:1:96)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jimmydev\NodeBB\node_modules\jsdom\lib\jsdom\browser\index.js:5:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)

**Comment by Holyphoenix** [comment]
This seems like a node-gyp issue.  I'm going to see if I can fix it by installing various microsoft .net stuff.

**Comment by Holyphoenix** [comment]
Yep, worked after installing Visual Studio 2015.  Installing just VC++ tools was not enough.
