### ISSUE TITLE
Error: Cannot find module 'internal/errors'

### ISSUE THREAD

**Issue by Kavatch** [akhoury/nodebb-plugin-import#218]
Every time I try to export my database I get this Error:

> 25/10 17:45 [13034] - error: Error: Cannot find module 'internal/errors'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:36:16
    at Object.<anonymous> (/root/nodebb/node_modules/npm/node_modules/graceful-fs/fs.js:11:8)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/nodebb/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
Error: Cannot find module 'internal/errors'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:36:16
    at Object.<anonymous> (/root/nodebb/node_modules/npm/node_modules/graceful-fs/fs.js:11:8)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/nodebb/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)

I have done everything I could think of and everything from the first two pages of google... I reainstalled node and npm 5 times and with differed methodes, I reinstalled nodebb and even resettet the whole server. So are there any thinks left I could do?

**Comment by t0rched** [comment]
Use nodejs 6.x...

**Comment by akhoury** [comment]
thanks @KipperedSnack
