### ISSUE TITLE
Type Error - Redis internal_send_command

### ISSUE THREAD

**Issue by hansbonini** [akhoury/nodebb-plugin-import#220]
```purgeMessagesStart ::: 0/1, 0%2018-04-01T17:07:16.495Z [27054] - error:  TypeError: this.internal_send_command is not a function
    at Object.keys (/home/hans/dev/rhbr/node_modules/redis/lib/commands.js:58:25)
    at Object.Messages.count (/home/hans/dev/rhbr/node_modules/nodebb-plugin-import/server/augmented/messages.js:128:8)
    at /home/hans/dev/rhbr/node_modules/nodebb-plugin-import/server/importer/index.js:323:19
    at /home/hans/dev/rhbr/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:607:21
    at /home/hans/dev/rhbr/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:246:17
    at iterate (/home/hans/dev/rhbr/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:146:13)
    at /home/hans/dev/rhbr/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:157:25
    at /home/hans/dev/rhbr/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:248:21
    at /home/hans/dev/rhbr/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:612:34
    at /home/hans/dev/rhbr/node_modules/nodebb-plugin-import/server/importer/index.js:315:15
    at /home/hans/dev/rhbr/node_modules/async/dist/async.js:958:16
    at next (/home/hans/dev/rhbr/node_modules/async/dist/async.js:5211:18)
    at /home/hans/dev/rhbr/src/batch.js:59:14
    at nextTask (/home/hans/dev/rhbr/node_modules/async/dist/async.js:5310:14)
    at next (/home/hans/dev/rhbr/node_modules/async/dist/async.js:5317:9)
    at /home/hans/dev/rhbr/node_modules/async/dist/async.js:958:16
```

**Comment by akhoury** [comment]
which redis version are you using?

**Comment by Armadill0** [comment]
Looks like I got a similar issue:
`[nodebb-plugin-import] importer.success [2020-01-04T22:46:05.929Z] Phase ::: usersImportStart

(node:942) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

[nodebb-plugin-import] importer.success [2020-01-04T22:46:05.949Z] Importing 105 users.

[nodebb-plugin-import] importer.success [2020-01-04T22:46:06.106Z] Imported 105/105 users (out of which 105 were already imported at an earlier time)
2020-01-04T22:46:06.110Z [4567/942] - ESC[31merrorESC[39m: uncaughtException: this.internal_send_command is not a function
TypeError: this.internal_send_command is not a function
    at Object.keys (/home/nodebb/nodebb/node_modules/redis/lib/commands.js:58:25)
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js:735:18
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:567:21
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:246:17
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:122:13
    at _each (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:46:13)
    at async.each (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:216:23)
    at _parallel (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:565:20)
    at Object.async.parallel (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:595:9)
    at Importer.exporter.exportUsers (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js:733:17)
    at Object.async.whilst (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:683:13)
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:679:23
    at Exporter.(anonymous function) (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/exporter/index.js:738:20)
    at onUsers (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/exporter/index.js:298:14) {"error":{},"stack":"TypeError: this.internal_send_command is not a function
    at Object.keys (/home/nodebb/nodebb/node_modules/redis/lib/commands.js:58:25)
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js:735:18
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:567:21
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:246:17
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:122:13
    at _each (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:46:13)
    at async.each (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:216:23)
    at _parallel (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:565:20)
    at Object.async.parallel (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:595:9)
    at Importer.exporter.exportUsers (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js:733:17)
    at Object.async.whilst (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:683:13)
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:679:23
    at Exporter.(anonymous function) (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/exporter/index.js:738:20)
    at onUsers (/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/exporter/index.js:298:14)","exception":true,"date":"Sat Jan 04 2020 23:46:06 GMT+0100 (Central European Standard Time)","process":{"pid":942,"uid":5007,"gid":5007,"cwd":"/home/nodebb/nodebb","execPath":"/usr/bin/node","version":"v10.16.3","argv":["/usr/bin/node","/home/nodebb/nodebb/app.js"],"memoryUsage":{"rss":293421056,"heapTotal":243810304,"heapUsed":184133200,"external":2361771}},"os":{"loadavg":[1.7177734375,0.6630859375,0.3232421875],"uptime":39754},"trace":[{"column":25,"file":"/home/nodebb/nodebb/node_modules/redis/lib/commands.js","function":"Object.keys","line":58,"method":"keys","native":false},{"column":18,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js","function":null,"line":735,"method":null,"native":false},{"column":21,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":null,"line":567,"method":null,"native":false},{"column":17,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":null,"line":246,"method":null,"native":false},{"column":13,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":null,"line":122,"method":null,"native":false},{"column":13,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":"_each","line":46,"method":null,"native":false},{"column":9,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":"async.each","line":121,"method":"each","native":false},{"column":13,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":"_asyncMap","line":245,"method":null,"native":false},{"column":23,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":"Object.map","line":216,"method":"map","native":false},{"column":20,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":"_parallel","line":565,"method":null,"native":false},{"column":9,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":"Object.async.parallel","line":595,"method":"parallel","native":false},{"column":17,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js","function":"Importer.exporter.exportUsers","line":733,"method":"exportUsers","native":false},{"column":13,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":"Object.async.whilst","line":683,"method":"whilst","native":false},{"column":23,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js","function":null,"line":679,"method":null,"native":false},{"column":20,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/exporter/index.js","function":"Exporter.(anonymous function)","line":738,"method":"(anonymous function)","native":false},{"column":14,"file":"/home/nodebb/nodebb/node_modules/nodebb-plugin-import/server/exporter/index.js","function":"onUsers","line":298,"method":null,"native":false}]}
2020-01-04T22:46:06.110Z [4567/942] - ESC[31merrorESC[39m: this.internal_send_command is not a function
2020-01-04T22:46:06.111Z [4567/942] - ESC[32minfoESC[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2020-01-04T22:46:06.114Z [4567/942] - ESC[32minfoESC[39m: [app] Web server closed to connections.`

OS: CentOS 8
NodeJS: 10.16.3
Redis: 5.0.3

**Comment by TheFitzZZ** [comment]
Did you overcome this at some point? I tried redis 6 down to 4, same result :-(

**Comment by Armadill0** [comment]
It does not seem to be related to the Redis server version at all but how the redis client is being used.

I think I found a fix with AI. I'll file a PR soon.
