### ISSUE TITLE
TypeError: callFn.apply is not a function

### ISSUE THREAD

**Issue by signal15** [akhoury/nodebb-plugin-import#221]
I'm using the smf importer.  Users and categories seem to import fine, but it fails when it tries to start importing messages.  Running branch 1.10.x of nodebb, nodejs 8.11.3, and npm 5.6.0.  I tried disabling all plugins and reinstalling the import and import-smf plugin, and get the same result.

`
[nodebb-plugin-import] importer.success [2018-07-20T04:16:52.099Z] Importing 2934 messages.
[nodebb-plugin-import-smf] getPaginatedMessages
exporter.log [2018-07-20T04:16:52.100Z] getPaginatedMessages
2018-07-20T04:16:52.550Z [26402] - error:  message=callFn.apply is not a function, stack=TypeError: callFn.apply is not a function
    at /home/ubuntu/nodebb/node_modules/async/dist/async.js:473:16
    at next (/home/ubuntu/nodebb/node_modules/async/dist/async.js:5329:29)
    at /home/ubuntu/nodebb/node_modules/async/dist/async.js:969:16
    at Object.Messaging.checkContent (/home/ubuntu/nodebb/src/messaging/create.js:31:11)
    at /home/ubuntu/nodebb/src/messaging/create.js:49:15
    at nextTask (/home/ubuntu/nodebb/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/home/ubuntu/nodebb/node_modules/async/dist/async.js:5334:5)
    at Object.Messaging.addMessage (/home/ubuntu/nodebb/src/messaging/create.js:47:9)
    at addMessage (/home/ubuntu/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js:963:31)
    at /home/ubuntu/nodebb/node_modules/nodebb-plugin-import/server/importer/index.js:940:25
    at /home/ubuntu/nodebb/node_modules/nodebb-plugin-import/server/augmented/messages.js:92:11
    at /home/ubuntu/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:251:17
    at done (/home/ubuntu/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:132:19)
    at /home/ubuntu/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:32:16
    at /home/ubuntu/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:248:21
    at /home/ubuntu/nodebb/node_modules/nodebb-plugin-import/node_modules/async/lib/async.js:572:34
    at /home/ubuntu/nodebb/node_modules/async/dist/async.js:473:16
    at next (/home/ubuntu/nodebb/node_modules/async/dist/async.js:5329:29)
    at /home/ubuntu/nodebb/node_modules/async/dist/async.js:969:16
    at /home/ubuntu/nodebb/src/messaging/rooms.js:23:5
    at nextTask (/home/ubuntu/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/home/ubuntu/nodebb/node_modules/async/dist/async.js:5331:9)
2018-07-20T04:16:52.559Z [26402] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
`

**Comment by akhoury** [comment]
answered here: https://github.com/a5mith/nodebb-plugin-import-smf/issues/10#issuecomment-406803456

**Comment by akhoury** [comment]
if that fixes it, then we can close it. I am upping support to 1.10 soon
