### ISSUE TITLE
nodebb-plugin-import error at nodebb start (TypeError: path must be a string or Buffer)

### ISSUE THREAD

**Issue by alfazaz** [akhoury/nodebb-plugin-import#222]
Hello !

I want to try a migration from phpbb2 to nodebb and I fail at the first step : I can't get nodebb-plugin-import working... This is what I do : 
- Install of nodebb v1.7.5 (asked for this plugin, instead of v1.10.1) with mongodb and nodejs-lts-carbon (all from scratch).
- Initial setup and starting of nodebb and it works.
- In the nodebb directory, npm install nodebb-plugin-import.
- Activation of nodebb-plugin-import in plugins and reload of nodebb in dev mode... and nodebb doesn't load nodebb-plugin-import with these messages : 

```
2018-08-17T16:13:50.449Z [20465] - error: TypeError: path must be a string or Buffer
    at Object.fs.readdirSync (fs.js:904:18)
    at getSiblingDirectories (/opt/nodebb/node_modules/nodebb-plugin-require/index.js:48:19)
    at findPackageDirectory (/opt/nodebb/node_modules/nodebb-plugin-require/index.js:25:20)
    at findNodebbDirectory (/opt/nodebb/node_modules/nodebb-plugin-require/index.js:59:9)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-require/index.js:62:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-import/server/index.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
2018-08-17T16:13:50.450Z [20465] - warn: [plugins] Unable to parse library for: nodebb-plugin-import
2018-08-17T16:13:50.450Z [20465] - verbose: [plugins] Loaded plugin: nodebb-plugin-import
```

and I can't access to any interface to play with import in nodebb (I also tried with other versions of nodebb (1.5.x), nodejs (10)...).

If I do after this in the node_modules/nodebb-plugin-import directory the command
npm install
and if I reload nodebb, it fails too with these messages : 

```
2018-08-17T16:34:48.654Z [20834] - error: TypeError: path must be a string or Buffer
    at Object.fs.readdirSync (fs.js:904:18)
    at getSiblingDirectories (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:48:19)
    at findPackageDirectory (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:25:20)
    at findNodebbDirectory (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:59:9)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:62:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-import/server/index.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
2018-08-17T16:34:48.654Z [20834] - warn: [plugins] Unable to parse library for: nodebb-plugin-import
```

Is it a bug ? I make a mistake ? If so, Which one ?? How I must activate and enjoy this plugin ?

Thanks !

**Comment by akhoury** [comment]
i will check it

**Comment by alfazaz** [comment]
Thank you. I will give any other information if needed.

**Comment by akhoury** [comment]
I can't reproduce the issue, are you sure you have `v1.7.5` installed? what's the output of 

```bash
git status
```

how did you install v1.7.5

```bash
git checkout v1.7.5
./nodebb setup
```

**Comment by alfazaz** [comment]
I installed v1.7.5 with
'''
sudo git clone -b v1.7.5 https://github.com/NodeBB/NodeBB.git nodebb
'''
package.json and logs of nodebb confirm v1.7.5.

Anyway, I have this (in the nodebb directory) : 
'''
[yannick@xps nodebb ]$ sudo git status
Actuellement sur aucun branche.
rien à valider, la copie de travail est propre
'''
It's in french but it means that I'm not on any branch but I think it's normal because of my install with the -b flag of git.

Then, now, I've done : 
'''
[yannick@xps nodebb ]$ sudo git checkout v1.7.5
HEAD est maintenant sur 7df191412 Incrementing version number - v1.7.5
'''
Then, I've done another nodebb setup and no change... Here are the logs : 
'''
[yannick@xps nodebb ]$ sudo ./nodebb setup
2018-08-19T16:48:20.650Z [4943] - info: NodeBB Setup Triggered via Command Line

Welcome to NodeBB v1.7.5!

This looks like a new installation, so you'll have to answer a few questions about your environment before we can proceed.
Press enter to accept the default setting (shown in brackets).
2018-08-19T16:48:20.732Z [4943] - info: 
Now configuring mongo database:
2018-08-19T16:48:20.978Z [4943] - info: [database] Checking database indices.
2018-08-19T16:48:20.987Z [4943] - info: [database] Checking database indices done!
Configuration Saved OK
Populating database with default configs, if not already set...
Previous theme detected, skipping enabling default theme
Categories OK. Found 4 categories.
Administrator found, skipping Admin setup
2018-08-19T16:48:21.500Z [4943] - info: Global Moderators group found, skipping creation!
Enabling default plugins
2018-08-19T16:48:21.507Z [4943] - info: [install/defaultPlugins] customDefaults
2018-08-19T16:48:21.508Z [4943] - info: [install/enableDefaultPlugins] activating default plugins 0=nodebb-plugin-composer-default, 1=nodebb-plugin-markdown, 2=nodebb-plugin-mentions, 3=nodebb-widget-essentials, 4=nodebb-rewards-essentials, 5=nodebb-plugin-soundpack-default, 6=nodebb-plugin-emoji, 7=nodebb-plugin-emoji-android
  started
2018-08-19T16:48:21.548Z [4943] - info: [build] Building in parallel mode
2018-08-19T16:48:21.549Z [4943] - info: [build]         plugin static dirs  build started
2018-08-19T16:48:21.551Z [4943] - info: [build]          requirejs modules  build started
2018-08-19T16:48:21.552Z [4943] - info: [build]           client js bundle  build started
2018-08-19T16:48:21.553Z [4943] - info: [build]            admin js bundle  build started
2018-08-19T16:48:21.553Z [4943] - info: [build]         client side styles  build started
2018-08-19T16:48:21.554Z [4943] - info: [build] admin control panel styles  build started
2018-08-19T16:48:21.554Z [4943] - info: [build]                  templates  build started
2018-08-19T16:48:21.555Z [4943] - info: [build]                  languages  build started
2018-08-19T16:48:21.555Z [4943] - info: [build]                     sounds  build started
2018-08-19T16:48:21.776Z [4943] - info: [build]                     sounds  build completed in 0.221sec
2018-08-19T16:48:21.864Z [4943] - info: [build]         plugin static dirs  build completed in 0.315sec
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
2018-08-19T16:48:24.793Z [4943] - info: [build]                  languages  build completed in 3.237sec
2018-08-19T16:48:24.807Z [4943] - info: [build]                  templates  build completed in 3.253sec
2018-08-19T16:48:25.178Z [4943] - info: [build]            admin js bundle  build completed in 3.625sec
2018-08-19T16:48:25.185Z [4943] - info: [build]           client js bundle  build completed in 3.632sec
2018-08-19T16:48:25.865Z [4943] - info: [build]         client side styles  build completed in 4.312sec
2018-08-19T16:48:25.980Z [4943] - info: [build]          requirejs modules  build completed in 4.429sec
2018-08-19T16:48:26.264Z [4943] - info: [build] admin control panel styles  build completed in 4.71sec
2018-08-19T16:48:26.265Z [4943] - info: [build] Asset compilation successful. Completed in 4.716sec.

     =========================================================================================================

NodeBB Setup Completed. Run "./nodebb start" to manually start your NodeBB server.
'''
And when I restart : 
'''
[yannick@xps nodebb ]$ sudo ./nodebb dev

NodeBB v1.7.5 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

2018-08-19T16:49:12.806Z [5108] - info: Initializing NodeBB v1.7.5 http://localhost:4567
2018-08-19T16:49:12.808Z [5108] - verbose: * using mongo store at 127.0.0.1:27017
2018-08-19T16:49:12.808Z [5108] - verbose: * using themes stored in: /opt/nodebb/node_modules
2018-08-19T16:49:13.550Z [5108] - verbose: [minifier] utilizing a maximum of 7 additional threads
2018-08-19T16:49:13.563Z [5108] - verbose: Checking dependencies for outdated modules
2018-08-19T16:49:13.764Z [5108] - verbose: [notifications.init] Registering jobs.
2018-08-19T16:49:13.764Z [5108] - verbose: [user/jobs] (Re-)starting user jobs...
2018-08-19T16:49:13.765Z [5108] - verbose: [user/jobs] Starting job (digest.daily)
2018-08-19T16:49:13.767Z [5108] - verbose: [user/jobs] Starting job (digest.weekly)
2018-08-19T16:49:13.767Z [5108] - verbose: [user/jobs] Starting job (digest.monthly)
2018-08-19T16:49:13.767Z [5108] - verbose: [user/jobs] Starting job (reset.clean)
2018-08-19T16:49:13.768Z [5108] - verbose: [user/jobs] 4 jobs started
2018-08-19T16:49:13.768Z [5108] - verbose: [emailer] Setting up SMTP fallback transport
2018-08-19T16:49:13.794Z [5108] - verbose: [emailer] Built custom email templates
2018-08-19T16:49:13.794Z [5108] - info: [themes] Using theme nodebb-theme-persona
2018-08-19T16:49:13.794Z [5108] - verbose: [plugins] Initializing plugins system
2018-08-19T16:49:13.799Z [5108] - verbose: [plugins] Loaded plugin: nodebb-plugin-composer-default
2018-08-19T16:49:13.800Z [5108] - verbose: [plugins] Loaded plugin: nodebb-theme-persona
2018-08-19T16:49:13.820Z [5108] - verbose: [plugins] Loaded plugin: nodebb-plugin-markdown
2018-08-19T16:49:13.832Z [5108] - verbose: [plugins] Loaded plugin: nodebb-plugin-mentions
2018-08-19T16:49:13.834Z [5108] - verbose: [plugins] Loaded plugin: nodebb-widget-essentials
2018-08-19T16:49:13.838Z [5108] - verbose: [plugins] Loaded plugin: nodebb-rewards-essentials
2018-08-19T16:49:13.839Z [5108] - verbose: [plugins] Found 3 sound file(s) for plugin nodebb-plugin-soundpack-default
2018-08-19T16:49:13.839Z [5108] - verbose: [plugins] Loaded plugin: nodebb-plugin-soundpack-default
2018-08-19T16:49:13.936Z [5108] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji
2018-08-19T16:49:13.953Z [5108] - verbose: [plugins] Loaded plugin: nodebb-plugin-emoji-android
2018-08-19T16:49:13.957Z [5108] - error: TypeError: path must be a string or Buffer
    at Object.fs.readdirSync (fs.js:904:18)
    at getSiblingDirectories (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:48:19)
    at findPackageDirectory (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:25:20)
    at findNodebbDirectory (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:59:9)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-import/node_modules/nodebb-plugin-require/index.js:62:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-import/server/index.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
2018-08-19T16:49:13.957Z [5108] - warn: [plugins] Unable to parse library for: nodebb-plugin-import
2018-08-19T16:49:13.957Z [5108] - verbose: [plugins] Loaded plugin: nodebb-plugin-import

2018-08-19T16:49:13.958Z [5108] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-composer-default

2018-08-19T16:49:13.958Z [5108] - info: [plugins] Plugins OK
2018-08-19T16:49:14.004Z [5108] - verbose: [hotswap] Router with id `plugins` replaced successfully
2018-08-19T16:49:14.004Z [5108] - verbose: [plugins] All plugins reloaded and rerouted
2018-08-19T16:49:14.006Z [5108] - verbose: [hotswap] Router with id `auth` replaced successfully
2018-08-19T16:49:14.006Z [5108] - info: Routes added
2018-08-19T16:49:14.009Z [5108] - verbose: [meta/blacklist] Loading 0 blacklist rule(s)
2018-08-19T16:49:14.009Z [5108] - info: NodeBB Ready
2018-08-19T16:49:14.011Z [5108] - info: Enabling 'trust proxy'
2018-08-19T16:49:14.016Z [5108] - info: NodeBB is now listening on: 0.0.0.0:4567
'''

So, there is again the error... ????
If you have a precise protocol to follow to test, I can do it (I'm on up to date archlinux, with nodejs-carbon-lts but I can change it if necessary ; when I tried nodejs 10, I had the error too...).

It's really strange...

**Comment by alfazaz** [comment]
Finally, no problem if I think about doing ./nodedd build before start...

I can close this issue. Thanks.
