### ISSUE TITLE
Error on plugin install (error on iconv@2.3.4 step)

### ISSUE THREAD

**Issue by alfazaz** [akhoury/nodebb-plugin-import#229]
Hello !

I try to install nodebb-plugin-import on my archlinux system and it fails (it was ok on last year)... Here are the logs :

```
[yannick@xps nodebb ]$ npm install nodebb-plugin-import       
npm WARN deprecated to-markdown@3.1.1: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown

> iconv@2.3.4 install /home/yannick/MPstarClem_Dev/nodebb/node_modules/iconv
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'fstream'
gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:690:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:25:18)
gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/entry.js:14:15)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:776:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:653:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
gyp ERR! System Linux 5.2.3-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/yannick/MPstarClem_Dev/nodebb/node_modules/iconv
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN textcomplete.contenteditable@0.1.1 requires a peer of textcomplete@^0.14.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! iconv@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the iconv@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yannick/.npm/_logs/2019-07-30T14_14_00_200Z-debug.log
```

I also attach the log file 2019-07-30T14_14_00_200Z-debug.log :
[2019-07-30T14_14_00_200Z-debug.log](https://github.com/akhoury/nodebb-plugin-import/files/3447226/2019-07-30T14_14_00_200Z-debug.log)

What do you think about it and what can I do to solve this problem ? Thanks in advance !

**Comment by alfazaz** [comment]
Finally, I passed this step replacing iconv with iconv-lite... I will see if there are problems after this.
